# Generated by Django 4.2.1 on 2023-05-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='Изображение')),
                ('product_price', models.IntegerField(max_length=150, verbose_name='Цена за покупку')),
                ('date_of_creation', models.DateField(max_length=150, verbose_name='Дата создания')),
                ('date_of_change', models.DateField(max_length=150, verbose_name='Дата последнего изменения')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'продукция',
                'verbose_name_plural': 'продукции',
                'ordering': ('description',),
            },
        ),
    ]
