# Generated by Django 4.2.1 on 2023-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_date_of_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена за покупку'),
        ),
    ]
