# Generated by Django 4.2.1 on 2023-06-01 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('user_lastname', models.CharField(max_length=150, verbose_name='Отчество')),
                ('user_surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('user_name',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_slug', models.CharField(max_length=250, verbose_name='Slug')),
                ('message_heading', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('message_content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('message_preview', models.ImageField(blank=True, null=True, upload_to='message_preview/', verbose_name='Превью')),
                ('date_of_creation', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('date_of_change', models.DateField(default=datetime.date.today, verbose_name='Дата последнего изменения')),
                ('is_publication', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Записи блога',
                'ordering': ('message_heading',),
            },
        ),
    ]
