# Generated by Django 4.2.1 on 2023-06-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_users_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
