# Generated by Django 4.2.1 on 2023-06-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_blog_user_name_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='message_slug',
            new_name='slug',
        ),
    ]
